apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod-p1
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1" 
spec:
  description: Ambiente de Produção

  sourceRepos:
    - '*'

  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
