apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-d1
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0" 
spec:
  project: prod-p1

  source:
    repoURL: https://github.com/paulo-fabiano/task-list-devops.git
    path: k8s/manifests/application

  destination:
    server: https://kubernetes.default.svc
    namespace: task-list-devops

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
